name: RDP via Ngrok

on:
  workflow_dispatch:

jobs:
  rdp:
    runs-on: windows-2022
    timeout-minutes: 360

    steps:
      - name: Enable RDP
        run: |
          Write-Host "🔧 Enabling RDP..."
          Set-ItemProperty -Path 'HKLM:\System\CurrentControlSet\Control\Terminal Server' -Name "fDenyTSConnections" -Value 0 -Force
          Enable-NetFirewallRule -DisplayGroup "Remote Desktop"

      - name: Create RDP User
        run: |
          Write-Host "👤 Creating RDP user..."
          $pass = [guid]::NewGuid().ToString('N').Substring(0,10) + "!"
          $sec = ConvertTo-SecureString $pass -AsPlainText -Force
          New-LocalUser -Name "rdpuser" -Password $sec -AccountNeverExpires
          Add-LocalGroupMember -Group "Administrators" -Member "rdpuser"
          Add-LocalGroupMember -Group "Remote Desktop Users" -Member "rdpuser"
          echo "RDP_USER=rdpuser" >> $env:GITHUB_ENV
          echo "RDP_PASS=$pass" >> $env:GITHUB_ENV
          Write-Host "✅ User: rdpuser / $pass"

      - name: Install Ngrok
        run: |
          Write-Host "⬇️ Installing ngrok..."
          Invoke-WebRequest -Uri https://bin.equinox.io/c/bNyj1mQVY4c/ngrok-stable-windows-amd64.zip -OutFile ngrok.zip
          Expand-Archive ngrok.zip -DestinationPath $env:ProgramData
          Remove-Item ngrok.zip
          & "$env:ProgramData\ngrok.exe" version

      - name: Connect Ngrok (TCP)
        env:
          NGROK_AUTH_TOKEN: ${{ secrets.NGROK_AUTH_TOKEN }}
        run: |
          Write-Host "🌐 Starting ngrok tunnel..."
          & "$env:ProgramData\ngrok.exe" authtoken $env:NGROK_AUTH_TOKEN
          Start-Process -FilePath "$env:ProgramData\ngrok.exe" -ArgumentList "tcp 3389" -WindowStyle Hidden
          Start-Sleep -Seconds 8
          $url = (Invoke-RestMethod -Uri "http://127.0.0.1:4040/api/tunnels").tunnels.public_url
          echo "NGROK_URL=$url" >> $env:GITHUB_ENV
          Write-Host "✅ Ngrok tunnel active: $url"

      - name: Show RDP Info
        run: |
          Write-Host "`n=============================="
          Write-Host "🖥️  Remote Desktop Access Info"
          Write-Host "RDP Host: $env:NGROK_URL"
          Write-Host "Username: $env:RDP_USER"
          Write-Host "Password: $env:RDP_PASS"
          Write-Host "==============================`n"

      - name: Keep Alive
        run: |
          while ($true) {
              Write-Host "[$(Get-Date)] RDP active..."
              Start-Sleep -Seconds 300
          }
